const router = require('express').Router();
const controller = require('./bonus.controller');
const { requireAuthentication } = require('../../middleware/authentication');
const { allowRoles, requirePermission } = require('../../middleware/authorization');
router.use(requireAuthentication);
router.get('/', allowRoles('admin_player', 'player', 'validator', 'player_validator'), controller.showList);
router.post('/', requirePermission('createBonuses'), controller.create);
router.get('/:id', allowRoles('admin_player', 'player', 'validator', 'player_validator'), controller.showDetail);
router.post('/:id/edit', requirePermission('createBonuses'), controller.update);
router.post('/:id/void', requirePermission('createBonuses'), controller.voidBonus);
module.exports = router;
